/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import CONTROL.ControlAluno;
import MODEL.ModelAluno;
import java.time.Period;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Bruno
 */
public class ViewAluno extends javax.swing.JFrame {

    private ControlAluno controlAluno;
    //private ControlProfessor controlProfessor;
    //private ArrayList<ModelProfessor> lstProfessores = new ArrayList();
    private ArrayList<ModelAluno> lstAlunoView = new ArrayList();
    private int iteracoesNaoSalvas = 0;
    private DefaultListModel<String> dlmTurmaView = new DefaultListModel<>();
    private Period pIdade;
   
    /**
     * Creates new form ViewAluno
     */
    public ViewAluno(ControlAluno cr) {
        this.controlAluno = cr;
        //controlProfessor = new ControlProfessor(false);
        //lstProfessores = controlProfessor.getLstProfessor();
        //System.out.println("Construtor " + lstProfessores.size());
        initComponents();

    }

    public String[] getDadosAluno() {
        String dadosTurma[] = new String[7];
        dadosTurma[0] = jtxtNome.getText();
        dadosTurma[1] = jtxtCpf.getText();
        dadosTurma[2] = jtxtEmail.getText();
        dadosTurma[3] = jtxtNascimento.getText();
        dadosTurma[4] = "" +pIdade.getYears();
        dadosTurma[5] = jtxtNomeResp.getText();
        dadosTurma[6] = jtxtCpfResp.getText();
        
        return dadosTurma;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbpPrincipal = new javax.swing.JTabbedPane();
        jpnlVisualizarMatricular = new javax.swing.JPanel();
        jpnlCadastrar = new javax.swing.JPanel();
        jpnlContainerDados = new javax.swing.JPanel();
        jlblNomeView = new javax.swing.JLabel();
        jlblCpfView = new javax.swing.JLabel();
        jlblEmailView = new javax.swing.JLabel();
        jlblNascimentoView = new javax.swing.JLabel();
        jtxtNome = new javax.swing.JTextField();
        jtxtCpf = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jtxtNascimento = new javax.swing.JFormattedTextField();
        jbtnCadastrar = new javax.swing.JButton();
        jbtnSalvar = new javax.swing.JButton();
        jbtnDescartar = new javax.swing.JButton();
        jbtnValidarIdade = new javax.swing.JButton();
        jlblStatus = new javax.swing.JLabel();
        jlblNomeResp = new javax.swing.JLabel();
        jlblCpfResp = new javax.swing.JLabel();
        jtxtNomeResp = new javax.swing.JTextField();
        jtxtCpfResp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jtbpPrincipal.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout jpnlVisualizarMatricularLayout = new javax.swing.GroupLayout(jpnlVisualizarMatricular);
        jpnlVisualizarMatricular.setLayout(jpnlVisualizarMatricularLayout);
        jpnlVisualizarMatricularLayout.setHorizontalGroup(
            jpnlVisualizarMatricularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        jpnlVisualizarMatricularLayout.setVerticalGroup(
            jpnlVisualizarMatricularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jtbpPrincipal.addTab("VISUALIZAR/MATRICULAR", jpnlVisualizarMatricular);

        jlblNomeView.setText("NOME");

        jlblCpfView.setText("CPF");

        jlblEmailView.setText("EMAIL");

        jlblNascimentoView.setText("NASCIMENTO");

        jtxtNome.setText("jTextField1");

        jtxtCpf.setText("jTextField2");

        jtxtEmail.setText("jTextField3");

        jtxtNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jbtnCadastrar.setText("CADASTRAR");
        jbtnCadastrar.setEnabled(false);
        jbtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCadastrarActionPerformed(evt);
            }
        });

        jbtnSalvar.setText("SALVAR");
        jbtnSalvar.setEnabled(false);

        jbtnDescartar.setText("DESCARTAR");
        jbtnDescartar.setEnabled(false);

        jbtnValidarIdade.setText("VERIFICAR");
        jbtnValidarIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnValidarIdadeActionPerformed(evt);
            }
        });

        jlblStatus.setText("É NECESSARIO VALIDAR A IDADE ANTES DE CADASTRAR");

        jlblNomeResp.setText("NOME RESPONSAVEL");
        jlblNomeResp.setEnabled(false);

        jlblCpfResp.setText("CPF RESPONSAVEL");
        jlblCpfResp.setEnabled(false);

        jtxtNomeResp.setText("jTextField1");
        jtxtNomeResp.setEnabled(false);

        jtxtCpfResp.setText("jTextField2");
        jtxtCpfResp.setEnabled(false);

        javax.swing.GroupLayout jpnlContainerDadosLayout = new javax.swing.GroupLayout(jpnlContainerDados);
        jpnlContainerDados.setLayout(jpnlContainerDadosLayout);
        jpnlContainerDadosLayout.setHorizontalGroup(
            jpnlContainerDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlContainerDadosLayout.createSequentialGroup()
                .addGroup(jpnlContainerDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlContainerDadosLayout.createSequentialGroup()
                        .addGroup(jpnlContainerDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnlContainerDadosLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jlblStatus))
                            .addGroup(jpnlContainerDadosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jlblNomeResp)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpnlContainerDadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpnlContainerDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlContainerDadosLayout.createSequentialGroup()
                                .addGroup(jpnlContainerDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpnlContainerDadosLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jbtnDescartar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jpnlContainerDadosLayout.createSequentialGroup()
                                        .addComponent(jlblNomeView)
                                        .addGap(231, 231, 231)))
                                .addGroup(jpnlContainerDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtxtNome)
                                    .addGroup(jpnlContainerDadosLayout.createSequentialGroup()
                                        .addComponent(jbtnSalvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtnCadastrar))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlContainerDadosLayout.createSequentialGroup()
                                .addGroup(jpnlContainerDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblCpfView)
                                    .addComponent(jlblEmailView)
                                    .addComponent(jlblNascimentoView, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jpnlContainerDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlContainerDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtxtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                        .addComponent(jtxtCpf))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlContainerDadosLayout.createSequentialGroup()
                                        .addComponent(jtxtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbtnValidarIdade))))
                            .addGroup(jpnlContainerDadosLayout.createSequentialGroup()
                                .addComponent(jlblCpfResp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtCpfResp, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlContainerDadosLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jtxtNomeResp, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jpnlContainerDadosLayout.setVerticalGroup(
            jpnlContainerDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlContainerDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlContainerDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNomeView)
                    .addComponent(jtxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlContainerDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCpfView)
                    .addComponent(jtxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlContainerDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblEmailView)
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlContainerDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNascimentoView)
                    .addComponent(jtxtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnValidarIdade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlContainerDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNomeResp)
                    .addComponent(jtxtNomeResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlContainerDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCpfResp)
                    .addComponent(jtxtCpfResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(jlblStatus)
                .addGap(18, 18, 18)
                .addGroup(jpnlContainerDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCadastrar)
                    .addComponent(jbtnSalvar)
                    .addComponent(jbtnDescartar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jpnlCadastrarLayout = new javax.swing.GroupLayout(jpnlCadastrar);
        jpnlCadastrar.setLayout(jpnlCadastrarLayout);
        jpnlCadastrarLayout.setHorizontalGroup(
            jpnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnlContainerDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(335, Short.MAX_VALUE))
        );
        jpnlCadastrarLayout.setVerticalGroup(
            jpnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnlContainerDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        jtbpPrincipal.addTab("CADASTRAR", jpnlCadastrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtbpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtbpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnValidarIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnValidarIdadeActionPerformed
        jbtnCadastrar.setEnabled(false);
        if (jtxtNascimento.isEnabled()) {
            
            try {
                jbtnCadastrar.setEnabled(true);
                pIdade = controlAluno.getIdade(jtxtNascimento.getText());
                System.out.println("IDADE: " + pIdade.getYears());
                jlblStatus.setText("IDADE: " + pIdade.getYears());
            } catch (Exception ex) {
                jlblStatus.setText(ex.getMessage());
                jbtnCadastrar.setEnabled(false);
                Logger.getLogger(ViewAluno.class.getName()).log(Level.SEVERE, null, ex);
            }
            jtxtNascimento.setEnabled(false);
            jbtnValidarIdade.setText("EDITAR");

            if (pIdade.getYears() < 18) {
                jlblNomeResp.setEnabled(true);
                jlblCpfResp.setEnabled(true);
                jtxtNomeResp.setEnabled(true);
                jtxtCpfResp.setEnabled(true);
            } else {
                jlblNomeResp.setEnabled(false);
                jlblCpfResp.setEnabled(false);
                jtxtNomeResp.setEnabled(false);
                jtxtCpfResp.setEnabled(false);
            }

        } else {
            jbtnCadastrar.setEnabled(false);
            jtxtNascimento.setEnabled(true);
            jbtnValidarIdade.setText("VALIDAR");
        }
    }//GEN-LAST:event_jbtnValidarIdadeActionPerformed

    private void jbtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCadastrarActionPerformed
        try {
            controlAluno.cadAluno();
            iteracoesNaoSalvas++;
            statusArquivo(true, iteracoesNaoSalvas + " alterações NÃO salvas.");
        } catch (Exception ex) {
            statusArquivo(false, ex.getMessage());
            Logger.getLogger(ViewAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnCadastrarActionPerformed

    public void statusArquivo(boolean estado, String message) {
        jbtnSalvar.setEnabled(estado);
        jbtnDescartar.setEnabled(estado);
        jlblStatus.setText(message);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnCadastrar;
    private javax.swing.JButton jbtnDescartar;
    private javax.swing.JButton jbtnSalvar;
    private javax.swing.JButton jbtnValidarIdade;
    private javax.swing.JLabel jlblCpfResp;
    private javax.swing.JLabel jlblCpfView;
    private javax.swing.JLabel jlblEmailView;
    private javax.swing.JLabel jlblNascimentoView;
    private javax.swing.JLabel jlblNomeResp;
    private javax.swing.JLabel jlblNomeView;
    private javax.swing.JLabel jlblStatus;
    private javax.swing.JPanel jpnlCadastrar;
    private javax.swing.JPanel jpnlContainerDados;
    private javax.swing.JPanel jpnlVisualizarMatricular;
    private javax.swing.JTabbedPane jtbpPrincipal;
    private javax.swing.JTextField jtxtCpf;
    private javax.swing.JTextField jtxtCpfResp;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JFormattedTextField jtxtNascimento;
    private javax.swing.JTextField jtxtNome;
    private javax.swing.JTextField jtxtNomeResp;
    // End of variables declaration//GEN-END:variables
}
